<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.32.1" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
		<ProjectReference Include="..\Services.Catalogs.Domain\Services.Catalogs.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Abstractions\Grpc\Clients\" />
		<Folder Include="Abstractions\Grpc\Servers\" />
		<Folder Include="Abstractions\HttpClients\" />
		<Folder Include="BusinessLogics\ActivityTypes\" />
		<Folder Include="BusinessLogics\MapObjects\" />
		<Folder Include="BusinessLogics\MasterSubjects\" />
		<Folder Include="Protos\" />
		<Folder Include="BusinessLogics\ObjectActivityTypes\" />
		<Folder Include="BusinessLogics\Subjects\" />
		<Folder Include="BusinessLogics\TaskLocations\" />
	</ItemGroup>
</Project>
