<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.72.0.3938" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.0" />
    <PackageReference Include="Google.Protobuf" Version="3.32.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\Services.Bundles.Domain\Services.Bundles.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\bundles.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
