apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sproutvrprovider-service-ingress
  labels:
    name: sproutvrprovider-service-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.129.212.248.220.nip.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sproutvrprovider-service-gateway-clusterip
                port:
                  number: 80
    - host: account.129.212.248.220.nip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: sproutvrprovider-service-account-clusterip
                port:
                  number: 80
