<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.5.4" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="payOS" Version="1.0.9" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
		<ProjectReference Include="..\..\..\Common\Common.Presentations\Common.Presentation.csproj" />
		<ProjectReference Include="..\Services.Payments.Application\Services.Payments.Application.csproj" />
		<ProjectReference Include="..\Services.Payments.Infrastructure\Services.Payments.Infrastructure.csproj" />
	</ItemGroup>

</Project>
