### Get orders via gateway
GET http://localhost:3000/orders/b0000001-0000-0000-0000-000000000001
Content-Type: application/json


### Get orders
GET http://localhost:7002/api/orders
Content-Type: application/json

### Get order by id
GET http://localhost:7002/api/orders/0199b72d-347d-72d5-9060-c00985b1aa3d
Content-Type: application/json

### Get order history
GET http://localhost:3000/orders/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhMDA4MC1lNzgzLTc0ZDgtYWVkZC04YWM5NTFmZWNiZjEiLCJlbWFpbCI6Im9yZ2FuaXphdGlvbjFAZXhhbXBsZS5jb20iLCJyb2xlIjoiT3JnYW5pemF0aW9uIiwibmFtZSI6IlRydW9uZyBUSFBUIEFCQyIsIm5iZiI6MTc2MDk0NTA2MiwiZXhwIjoxNzYwOTUyMjYyLCJpYXQiOjE3NjA5NDUwNjIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJodHRwOi8vbG9jYWxob3N0OjcwMDEiLCJodHRwOi8vbG9jYWxob3N0OjcwMDIiLCJodHRwOi8vbG9jYWxob3N0OjcwMDMiLCJodHRwOi8vbG9jYWxob3N0OjcwMDQiLCJodHRwOi8vbG9jYWxob3N0OjcwMDUiXX0.LxKPHu6A6Y-yOGjNKABo_axXn2yJv0e2ka3KHsqDLCY

### Get purchased map
GET http://localhost:3000/orders/purchased-maps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhMDA4MC1lNzgzLTc0ZDgtYWVkZC04YWM5NTFmZWNiZjEiLCJlbWFpbCI6Im9yZ2FuaXphdGlvbjFAZXhhbXBsZS5jb20iLCJyb2xlIjoiT3JnYW5pemF0aW9uIiwibmFtZSI6IlRydW9uZyBUSFBUIEFCQyIsIm5iZiI6MTc2MDk0NTA2MiwiZXhwIjoxNzYwOTUyMjYyLCJpYXQiOjE3NjA5NDUwNjIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJodHRwOi8vbG9jYWxob3N0OjcwMDEiLCJodHRwOi8vbG9jYWxob3N0OjcwMDIiLCJodHRwOi8vbG9jYWxob3N0OjcwMDMiLCJodHRwOi8vbG9jYWxob3N0OjcwMDQiLCJodHRwOi8vbG9jYWxob3N0OjcwMDUiXX0.LxKPHu6A6Y-yOGjNKABo_axXn2yJv0e2ka3KHsqDLCY