### Get Maps with pagination
GET http://localhost:3000/orders
Content-Type: application/json

### Get orders
GET http://localhost:5000/api/orders
Content-Type: application/json


### Get Maps with filters
GET http://localhost:7001/api/catalogs/maps?pageIndex=1&pageSize=10
Content-Type: application/json

### Get Map by ID
GET http://localhost:3000/catalogs/maps/a0000001-0000-0000-0000-000000000002
Content-Type: application/json

### Create Map
POST http://localhost:7001/api/catalogs/maps
Content-Type: application/json
{
  "subjectId": "10000001-0000-0000-0000-000000000002",
  "price": 99.99,
  "name": "Test Map",
  "description": "Test Description",
  "imageUrl": "https://example.com/image.jpg",
  "status": "Active",
  "mapCode": "MAP100"
}

### Update Map
PUT http://localhost:7001/api/catalogs/maps/a0000001-0000-0000-0000-000000000002
Content-Type: application/json
{
  "price": 149.99,
  "name": "Updated Map",
  "description": "Updated Description",
  "imageUrl": "https://example.com/updated-image.jpg",
  "status": "Active",
  "mapCode": "MAP001"
}

### Delete Map
DELETE http://localhost:7001/api/catalogs/maps/a0000001-0000-0000-0000-000000000002

