<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
	  <UserSecretsId>0c2f81b5-176a-4580-90c6-f68766cf3ce6</UserSecretsId>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <DockerfileContext>..\..\..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Services.Upload.Application\Services.Upload.Application.csproj" />
	  <ProjectReference Include="..\Services.Upload.Infrastructure\Services.Upload.Infrastructure.csproj" />
	</ItemGroup>


</Project>
