<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.32.1" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
		<ProjectReference Include="..\Services.Notifications.Domain\Services.Notifications.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\organizations.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\accounts.proto" GrpcServices="Client" />
	</ItemGroup>
</Project>
