<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Infrastructure\Common.Infrastructure.csproj" />
		<ProjectReference Include="..\Services.Catalogs.Application\Services.Catalogs.Application.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Data\Migrations\" />
		<Folder Include="Data\SeederFiles\" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Data\SeederFiles\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
