<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
		<ProjectReference Include="..\Services.Baskets.Domain\Services.Baskets.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Helpers\" />
		<Folder Include="Protocs\" />
	</ItemGroup>

</Project>
