<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
		<PackageReference Include="Google.Apis.Core" Version="1.72.0" />
		<PackageReference Include="Google.Apis.Drive.v3" Version="1.72.0.3938" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Infrastructure\Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Services.Bundles.Application\Services.Bundles.Application.csproj" />
  </ItemGroup>

</Project>
