<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.32.1" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
		<ProjectReference Include="..\Services.Orders.Domain\Services.Orders.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Abstractions\Grpc\Clients\" />
	  <Folder Include="Abstractions\Grpc\Servers\" />
	  <Folder Include="Abstractions\HttpClients\" />
	  <Folder Include="Abstractions\Services\" />
	  <Folder Include="BusinessLogics\" />
	  <Folder Include="Protos\" />
	</ItemGroup>
</Project>
